name: Release Deployment Tests

on:
  workflow_dispatch:

jobs:
  trigger-repo-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.HYGRAPH_RELEASES_APP_ID }}
          private-key: ${{ secrets.HYGRAPH_RELEASES_PRIVATE_KEY }}

      - name: Send repository_dispatch event to trigger-receive
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
            https://api.github.com/repos/deepakkt/trigger-receive/dispatches \
            -d '{"event_type": "trigger-e2e-tests", "client_payload": { "sha": "${{ github.sha }}", "branch": "${{ github.head_ref }}" }}'
